import type { RecipeInput, Ingredient, Difficulty } from "../../shared/types";

function ing(name: string, quantity: number, unit: string, category: Ingredient["category"]): Ingredient {
  return { name, quantity, unit, category };
}

export const SEED_RECIPES: RecipeInput[] = [
  // ── AMERICAN ──
  {
    title: "Classic Cheeseburgers",
    cuisine: "american",
    vegetarian: false,
    protein_type: "beef",
    cook_minutes: 25,
    allergens: ["gluten", "dairy"],
    kid_friendly: true,
    makes_leftovers: false,
    leftovers_score: 0,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["summer"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("ground beef", 1.5, "lb", "protein"),
      ing("burger buns", 4, "count", "grains"),
      ing("cheddar cheese", 4, "slices", "dairy"),
      ing("lettuce", 1, "head", "produce"),
      ing("tomato", 2, "count", "produce"),
      ing("onion", 1, "count", "produce"),
    ],
    tags: ["quick", "grilling"],
  },
  {
    title: "BBQ Pulled Pork",
    cuisine: "american",
    vegetarian: false,
    protein_type: "pork",
    cook_minutes: 180,
    allergens: ["gluten"],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 5,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["summer"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("pork shoulder", 3, "lb", "protein"),
      ing("bbq sauce", 1, "cup", "pantry"),
      ing("burger buns", 6, "count", "grains"),
      ing("coleslaw mix", 1, "bag", "produce"),
      ing("apple cider vinegar", 2, "tbsp", "pantry"),
    ],
    tags: ["slow-cook", "crowd-pleaser"],
  },
  {
    title: "Mac and Cheese",
    cuisine: "american",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 30,
    allergens: ["gluten", "dairy"],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["fall", "winter"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("elbow macaroni", 1, "lb", "grains"),
      ing("cheddar cheese", 2, "cups", "dairy"),
      ing("milk", 1, "cup", "dairy"),
      ing("butter", 3, "tbsp", "dairy"),
      ing("flour", 3, "tbsp", "pantry"),
    ],
    tags: ["comfort-food"],
  },
  {
    title: "Grilled Chicken Salad",
    cuisine: "american",
    vegetarian: false,
    protein_type: "chicken",
    cook_minutes: 20,
    allergens: [],
    kid_friendly: false,
    makes_leftovers: false,
    leftovers_score: 1,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["spring", "summer"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("chicken breast", 1.5, "lb", "protein"),
      ing("mixed greens", 6, "cups", "produce"),
      ing("cherry tomatoes", 1, "pint", "produce"),
      ing("cucumber", 1, "count", "produce"),
      ing("olive oil", 3, "tbsp", "pantry"),
      ing("lemon", 1, "count", "produce"),
    ],
    tags: ["healthy", "quick"],
  },

  // ── ITALIAN ──
  {
    title: "Spaghetti Bolognese",
    cuisine: "italian",
    vegetarian: false,
    protein_type: "beef",
    cook_minutes: 45,
    allergens: ["gluten"],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 5,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["fall", "winter"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("ground beef", 1, "lb", "protein"),
      ing("spaghetti", 1, "lb", "grains"),
      ing("crushed tomatoes", 28, "oz", "pantry"),
      ing("onion", 1, "count", "produce"),
      ing("garlic", 4, "cloves", "produce"),
      ing("olive oil", 2, "tbsp", "pantry"),
      ing("parmesan", 0.5, "cup", "dairy"),
    ],
    tags: ["classic", "comfort-food"],
  },
  {
    title: "Margherita Pizza",
    cuisine: "italian",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 35,
    allergens: ["gluten", "dairy"],
    kid_friendly: true,
    makes_leftovers: false,
    leftovers_score: 1,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("pizza dough", 1, "lb", "grains"),
      ing("mozzarella", 8, "oz", "dairy"),
      ing("tomato sauce", 0.5, "cup", "pantry"),
      ing("fresh basil", 1, "bunch", "produce"),
      ing("olive oil", 2, "tbsp", "pantry"),
    ],
    tags: ["classic"],
  },
  {
    title: "Chicken Parmesan",
    cuisine: "italian",
    vegetarian: false,
    protein_type: "chicken",
    cook_minutes: 40,
    allergens: ["gluten", "dairy"],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("chicken breast", 1.5, "lb", "protein"),
      ing("breadcrumbs", 1, "cup", "pantry"),
      ing("mozzarella", 8, "oz", "dairy"),
      ing("marinara sauce", 2, "cups", "pantry"),
      ing("spaghetti", 0.5, "lb", "grains"),
      ing("parmesan", 0.5, "cup", "dairy"),
    ],
    tags: ["comfort-food"],
  },
  {
    title: "Pasta Primavera",
    cuisine: "italian",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 25,
    allergens: ["gluten"],
    kid_friendly: false,
    makes_leftovers: false,
    leftovers_score: 1,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["spring", "summer"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("penne pasta", 1, "lb", "grains"),
      ing("zucchini", 2, "count", "produce"),
      ing("bell pepper", 2, "count", "produce"),
      ing("cherry tomatoes", 1, "pint", "produce"),
      ing("garlic", 3, "cloves", "produce"),
      ing("olive oil", 3, "tbsp", "pantry"),
    ],
    tags: ["healthy", "quick"],
  },

  // ── MEXICAN ──
  {
    title: "Chicken Tacos",
    cuisine: "mexican",
    vegetarian: false,
    protein_type: "chicken",
    cook_minutes: 25,
    allergens: [],
    kid_friendly: true,
    makes_leftovers: false,
    leftovers_score: 1,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("chicken thighs", 1.5, "lb", "protein"),
      ing("corn tortillas", 12, "count", "grains"),
      ing("avocado", 2, "count", "produce"),
      ing("lime", 2, "count", "produce"),
      ing("cilantro", 1, "bunch", "produce"),
      ing("onion", 1, "count", "produce"),
      ing("cumin", 1, "tsp", "spices"),
      ing("chili powder", 1, "tsp", "spices"),
    ],
    tags: ["quick", "crowd-pleaser"],
  },
  {
    title: "Beef Burrito Bowls",
    cuisine: "mexican",
    vegetarian: false,
    protein_type: "beef",
    cook_minutes: 35,
    allergens: [],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("ground beef", 1, "lb", "protein"),
      ing("rice", 1.5, "cups", "grains"),
      ing("black beans", 15, "oz", "pantry"),
      ing("corn", 1, "cup", "produce"),
      ing("avocado", 2, "count", "produce"),
      ing("salsa", 1, "cup", "pantry"),
      ing("cumin", 1, "tsp", "spices"),
    ],
    tags: ["bowl"],
  },
  {
    title: "Black Bean Enchiladas",
    cuisine: "mexican",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 40,
    allergens: ["dairy"],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("black beans", 30, "oz", "pantry"),
      ing("corn tortillas", 12, "count", "grains"),
      ing("enchilada sauce", 2, "cups", "pantry"),
      ing("cheddar cheese", 2, "cups", "dairy"),
      ing("onion", 1, "count", "produce"),
      ing("cumin", 1, "tsp", "spices"),
    ],
    tags: ["comfort-food"],
  },
  {
    title: "Veggie Quesadillas",
    cuisine: "mexican",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 15,
    allergens: ["gluten", "dairy"],
    kid_friendly: true,
    makes_leftovers: false,
    leftovers_score: 0,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("flour tortillas", 8, "count", "grains"),
      ing("cheddar cheese", 2, "cups", "dairy"),
      ing("bell pepper", 2, "count", "produce"),
      ing("onion", 1, "count", "produce"),
      ing("black beans", 15, "oz", "pantry"),
    ],
    tags: ["quick", "kid-favorite"],
  },

  // ── INDIAN ──
  {
    title: "Chicken Tikka Masala",
    cuisine: "indian",
    vegetarian: false,
    protein_type: "chicken",
    cook_minutes: 45,
    allergens: ["dairy"],
    kid_friendly: false,
    makes_leftovers: true,
    leftovers_score: 5,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["fall", "winter"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("chicken thighs", 2, "lb", "protein"),
      ing("yogurt", 1, "cup", "dairy"),
      ing("crushed tomatoes", 14, "oz", "pantry"),
      ing("heavy cream", 0.5, "cup", "dairy"),
      ing("onion", 2, "count", "produce"),
      ing("garlic", 4, "cloves", "produce"),
      ing("ginger", 1, "inch", "produce"),
      ing("garam masala", 2, "tsp", "spices"),
      ing("turmeric", 1, "tsp", "spices"),
      ing("rice", 1.5, "cups", "grains"),
    ],
    tags: ["flavorful", "crowd-pleaser"],
  },
  {
    title: "Chana Masala",
    cuisine: "indian",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 30,
    allergens: [],
    kid_friendly: false,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("chickpeas", 30, "oz", "pantry"),
      ing("crushed tomatoes", 14, "oz", "pantry"),
      ing("onion", 2, "count", "produce"),
      ing("garlic", 4, "cloves", "produce"),
      ing("ginger", 1, "inch", "produce"),
      ing("garam masala", 2, "tsp", "spices"),
      ing("cumin", 1, "tsp", "spices"),
      ing("rice", 1.5, "cups", "grains"),
    ],
    tags: ["healthy", "vegan"],
  },
  {
    title: "Palak Paneer",
    cuisine: "indian",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 35,
    allergens: ["dairy"],
    kid_friendly: false,
    makes_leftovers: false,
    leftovers_score: 2,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("paneer", 14, "oz", "dairy"),
      ing("spinach", 1, "lb", "produce"),
      ing("onion", 1, "count", "produce"),
      ing("garlic", 3, "cloves", "produce"),
      ing("ginger", 1, "inch", "produce"),
      ing("garam masala", 1, "tsp", "spices"),
      ing("cumin", 1, "tsp", "spices"),
      ing("rice", 1.5, "cups", "grains"),
    ],
    tags: ["classic"],
  },
  {
    title: "Dal Tadka",
    cuisine: "indian",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 40,
    allergens: [],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["fall", "winter"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("red lentils", 1.5, "cups", "pantry"),
      ing("onion", 1, "count", "produce"),
      ing("garlic", 3, "cloves", "produce"),
      ing("tomato", 2, "count", "produce"),
      ing("turmeric", 1, "tsp", "spices"),
      ing("cumin seeds", 1, "tsp", "spices"),
      ing("rice", 1.5, "cups", "grains"),
    ],
    tags: ["vegan", "healthy"],
  },

  // ── CHINESE ──
  {
    title: "Chicken Stir-Fry",
    cuisine: "chinese",
    vegetarian: false,
    protein_type: "chicken",
    cook_minutes: 20,
    allergens: ["soy"],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 3,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("chicken breast", 1.5, "lb", "protein"),
      ing("broccoli", 2, "cups", "produce"),
      ing("bell pepper", 2, "count", "produce"),
      ing("soy sauce", 3, "tbsp", "pantry"),
      ing("sesame oil", 1, "tbsp", "pantry"),
      ing("garlic", 3, "cloves", "produce"),
      ing("ginger", 1, "inch", "produce"),
      ing("rice", 1.5, "cups", "grains"),
    ],
    tags: ["quick", "healthy"],
  },
  {
    title: "Beef and Broccoli",
    cuisine: "chinese",
    vegetarian: false,
    protein_type: "beef",
    cook_minutes: 25,
    allergens: ["soy"],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 3,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("flank steak", 1.5, "lb", "protein"),
      ing("broccoli", 3, "cups", "produce"),
      ing("soy sauce", 3, "tbsp", "pantry"),
      ing("oyster sauce", 2, "tbsp", "pantry"),
      ing("garlic", 3, "cloves", "produce"),
      ing("ginger", 1, "inch", "produce"),
      ing("rice", 1.5, "cups", "grains"),
    ],
    tags: ["classic", "quick"],
  },
  {
    title: "Vegetable Fried Rice",
    cuisine: "chinese",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 15,
    allergens: ["soy"],
    kid_friendly: true,
    makes_leftovers: false,
    leftovers_score: 1,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("rice", 3, "cups", "grains"),
      ing("eggs", 3, "count", "dairy"),
      ing("peas", 1, "cup", "frozen"),
      ing("carrots", 2, "count", "produce"),
      ing("soy sauce", 3, "tbsp", "pantry"),
      ing("sesame oil", 1, "tbsp", "pantry"),
      ing("green onions", 4, "count", "produce"),
    ],
    tags: ["quick", "kid-favorite"],
  },
  {
    title: "Kung Pao Tofu",
    cuisine: "chinese",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 25,
    allergens: ["soy", "nuts"],
    kid_friendly: false,
    makes_leftovers: false,
    leftovers_score: 1,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("firm tofu", 14, "oz", "protein"),
      ing("peanuts", 0.5, "cup", "pantry"),
      ing("bell pepper", 2, "count", "produce"),
      ing("soy sauce", 3, "tbsp", "pantry"),
      ing("rice vinegar", 2, "tbsp", "pantry"),
      ing("garlic", 3, "cloves", "produce"),
      ing("rice", 1.5, "cups", "grains"),
    ],
    tags: ["spicy"],
  },

  // ── JAPANESE ──
  {
    title: "Teriyaki Salmon",
    cuisine: "japanese",
    vegetarian: false,
    protein_type: "fish",
    cook_minutes: 20,
    allergens: ["soy", "fish"],
    kid_friendly: true,
    makes_leftovers: false,
    leftovers_score: 1,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("salmon fillets", 1.5, "lb", "protein"),
      ing("soy sauce", 3, "tbsp", "pantry"),
      ing("mirin", 2, "tbsp", "pantry"),
      ing("sugar", 1, "tbsp", "pantry"),
      ing("rice", 1.5, "cups", "grains"),
      ing("broccoli", 2, "cups", "produce"),
    ],
    tags: ["healthy", "quick"],
  },
  {
    title: "Chicken Katsu Curry",
    cuisine: "japanese",
    vegetarian: false,
    protein_type: "chicken",
    cook_minutes: 40,
    allergens: ["gluten"],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["fall", "winter"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("chicken breast", 1.5, "lb", "protein"),
      ing("panko breadcrumbs", 1, "cup", "pantry"),
      ing("curry roux", 1, "box", "pantry"),
      ing("potato", 2, "count", "produce"),
      ing("carrot", 2, "count", "produce"),
      ing("onion", 1, "count", "produce"),
      ing("rice", 2, "cups", "grains"),
    ],
    tags: ["comfort-food", "crowd-pleaser"],
  },
  {
    title: "Vegetable Ramen",
    cuisine: "japanese",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 30,
    allergens: ["gluten", "soy"],
    kid_friendly: true,
    makes_leftovers: false,
    leftovers_score: 0,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["fall", "winter"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("ramen noodles", 4, "packs", "grains"),
      ing("miso paste", 3, "tbsp", "pantry"),
      ing("mushrooms", 8, "oz", "produce"),
      ing("corn", 1, "cup", "produce"),
      ing("green onions", 4, "count", "produce"),
      ing("soft-boiled eggs", 4, "count", "dairy"),
      ing("sesame oil", 1, "tbsp", "pantry"),
    ],
    tags: ["comfort-food"],
  },

  // ── THAI ──
  {
    title: "Pad Thai",
    cuisine: "thai",
    vegetarian: false,
    protein_type: "shrimp",
    cook_minutes: 25,
    allergens: ["shellfish", "nuts", "soy"],
    kid_friendly: false,
    makes_leftovers: false,
    leftovers_score: 0,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("shrimp", 1, "lb", "protein"),
      ing("rice noodles", 8, "oz", "grains"),
      ing("eggs", 2, "count", "dairy"),
      ing("peanuts", 0.5, "cup", "pantry"),
      ing("bean sprouts", 2, "cups", "produce"),
      ing("lime", 2, "count", "produce"),
      ing("fish sauce", 3, "tbsp", "pantry"),
      ing("tamarind paste", 2, "tbsp", "pantry"),
    ],
    tags: ["classic"],
  },
  {
    title: "Green Curry with Chicken",
    cuisine: "thai",
    vegetarian: false,
    protein_type: "chicken",
    cook_minutes: 30,
    allergens: ["fish"],
    kid_friendly: false,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("chicken thighs", 1.5, "lb", "protein"),
      ing("green curry paste", 3, "tbsp", "pantry"),
      ing("coconut milk", 14, "oz", "pantry"),
      ing("bamboo shoots", 8, "oz", "pantry"),
      ing("thai basil", 1, "bunch", "produce"),
      ing("fish sauce", 2, "tbsp", "pantry"),
      ing("rice", 1.5, "cups", "grains"),
    ],
    tags: ["spicy", "flavorful"],
  },
  {
    title: "Vegetable Pad See Ew",
    cuisine: "thai",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 20,
    allergens: ["soy", "gluten"],
    kid_friendly: true,
    makes_leftovers: false,
    leftovers_score: 0,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("wide rice noodles", 1, "lb", "grains"),
      ing("broccoli", 2, "cups", "produce"),
      ing("eggs", 2, "count", "dairy"),
      ing("soy sauce", 3, "tbsp", "pantry"),
      ing("garlic", 3, "cloves", "produce"),
      ing("oyster sauce", 2, "tbsp", "pantry"),
    ],
    tags: ["quick"],
  },

  // ── MEDITERRANEAN ──
  {
    title: "Greek Chicken Bowl",
    cuisine: "mediterranean",
    vegetarian: false,
    protein_type: "chicken",
    cook_minutes: 30,
    allergens: ["dairy"],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["spring", "summer"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("chicken thighs", 1.5, "lb", "protein"),
      ing("rice", 1.5, "cups", "grains"),
      ing("cucumber", 1, "count", "produce"),
      ing("cherry tomatoes", 1, "pint", "produce"),
      ing("feta cheese", 4, "oz", "dairy"),
      ing("red onion", 0.5, "count", "produce"),
      ing("olive oil", 3, "tbsp", "pantry"),
      ing("lemon", 1, "count", "produce"),
      ing("oregano", 1, "tsp", "spices"),
    ],
    tags: ["healthy", "bowl"],
  },
  {
    title: "Falafel Wraps",
    cuisine: "mediterranean",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 35,
    allergens: ["gluten"],
    kid_friendly: false,
    makes_leftovers: true,
    leftovers_score: 3,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("chickpeas", 30, "oz", "pantry"),
      ing("pita bread", 6, "count", "grains"),
      ing("tahini", 0.25, "cup", "pantry"),
      ing("cucumber", 1, "count", "produce"),
      ing("tomato", 2, "count", "produce"),
      ing("onion", 1, "count", "produce"),
      ing("parsley", 1, "bunch", "produce"),
      ing("cumin", 1, "tsp", "spices"),
    ],
    tags: ["vegan-adaptable"],
  },
  {
    title: "Shakshuka",
    cuisine: "mediterranean",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 25,
    allergens: [],
    kid_friendly: true,
    makes_leftovers: false,
    leftovers_score: 0,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("eggs", 6, "count", "dairy"),
      ing("crushed tomatoes", 28, "oz", "pantry"),
      ing("onion", 1, "count", "produce"),
      ing("bell pepper", 2, "count", "produce"),
      ing("garlic", 3, "cloves", "produce"),
      ing("cumin", 1, "tsp", "spices"),
      ing("paprika", 1, "tsp", "spices"),
      ing("crusty bread", 1, "loaf", "grains"),
    ],
    tags: ["brunch-dinner", "quick"],
  },

  // ── KOREAN ──
  {
    title: "Bibimbap",
    cuisine: "korean",
    vegetarian: false,
    protein_type: "beef",
    cook_minutes: 35,
    allergens: ["soy"],
    kid_friendly: false,
    makes_leftovers: false,
    leftovers_score: 1,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("ground beef", 1, "lb", "protein"),
      ing("rice", 2, "cups", "grains"),
      ing("spinach", 4, "cups", "produce"),
      ing("carrots", 2, "count", "produce"),
      ing("zucchini", 1, "count", "produce"),
      ing("eggs", 4, "count", "dairy"),
      ing("soy sauce", 2, "tbsp", "pantry"),
      ing("sesame oil", 2, "tbsp", "pantry"),
      ing("gochujang", 2, "tbsp", "pantry"),
    ],
    tags: ["bowl", "colorful"],
  },
  {
    title: "Korean BBQ Pork",
    cuisine: "korean",
    vegetarian: false,
    protein_type: "pork",
    cook_minutes: 30,
    allergens: ["soy"],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["summer"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("pork belly", 1.5, "lb", "protein"),
      ing("soy sauce", 3, "tbsp", "pantry"),
      ing("sesame oil", 1, "tbsp", "pantry"),
      ing("garlic", 4, "cloves", "produce"),
      ing("ginger", 1, "inch", "produce"),
      ing("rice", 2, "cups", "grains"),
      ing("lettuce", 1, "head", "produce"),
      ing("kimchi", 1, "cup", "produce"),
    ],
    tags: ["grilling", "crowd-pleaser"],
  },
  {
    title: "Japchae",
    cuisine: "korean",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 25,
    allergens: ["soy"],
    kid_friendly: true,
    makes_leftovers: false,
    leftovers_score: 1,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("sweet potato noodles", 8, "oz", "grains"),
      ing("spinach", 4, "cups", "produce"),
      ing("carrots", 2, "count", "produce"),
      ing("mushrooms", 4, "oz", "produce"),
      ing("soy sauce", 3, "tbsp", "pantry"),
      ing("sesame oil", 2, "tbsp", "pantry"),
      ing("garlic", 3, "cloves", "produce"),
    ],
    tags: ["healthy"],
  },

  // ── FRENCH ──
  {
    title: "Chicken Provencal",
    cuisine: "french",
    vegetarian: false,
    protein_type: "chicken",
    cook_minutes: 50,
    allergens: [],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["summer", "fall"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("chicken thighs", 2, "lb", "protein"),
      ing("crushed tomatoes", 14, "oz", "pantry"),
      ing("olives", 0.5, "cup", "pantry"),
      ing("onion", 1, "count", "produce"),
      ing("garlic", 4, "cloves", "produce"),
      ing("herbes de provence", 1, "tbsp", "spices"),
      ing("white wine", 0.5, "cup", "pantry"),
      ing("crusty bread", 1, "loaf", "grains"),
    ],
    tags: ["classic", "one-pot"],
  },
  {
    title: "Ratatouille",
    cuisine: "french",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 50,
    allergens: [],
    kid_friendly: false,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["summer"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("eggplant", 1, "count", "produce"),
      ing("zucchini", 2, "count", "produce"),
      ing("bell pepper", 2, "count", "produce"),
      ing("tomato", 4, "count", "produce"),
      ing("onion", 1, "count", "produce"),
      ing("garlic", 4, "cloves", "produce"),
      ing("olive oil", 4, "tbsp", "pantry"),
      ing("herbes de provence", 1, "tbsp", "spices"),
    ],
    tags: ["healthy", "vegan"],
  },
  {
    title: "Quiche Lorraine",
    cuisine: "french",
    vegetarian: false,
    protein_type: "pork",
    cook_minutes: 55,
    allergens: ["gluten", "dairy"],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 3,
    difficulty: "hard",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["spring"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("pie crust", 1, "count", "grains"),
      ing("bacon", 8, "slices", "protein"),
      ing("eggs", 4, "count", "dairy"),
      ing("heavy cream", 1, "cup", "dairy"),
      ing("gruyere cheese", 1, "cup", "dairy"),
      ing("onion", 1, "count", "produce"),
    ],
    tags: ["brunch-dinner"],
  },

  // ── MIDDLE EASTERN ──
  {
    title: "Chicken Shawarma",
    cuisine: "middle_eastern",
    vegetarian: false,
    protein_type: "chicken",
    cook_minutes: 35,
    allergens: ["dairy"],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("chicken thighs", 2, "lb", "protein"),
      ing("pita bread", 6, "count", "grains"),
      ing("yogurt", 1, "cup", "dairy"),
      ing("cucumber", 1, "count", "produce"),
      ing("tomato", 2, "count", "produce"),
      ing("cumin", 2, "tsp", "spices"),
      ing("paprika", 1, "tsp", "spices"),
      ing("turmeric", 1, "tsp", "spices"),
    ],
    tags: ["crowd-pleaser", "flavorful"],
  },
  {
    title: "Lentil Soup",
    cuisine: "middle_eastern",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 35,
    allergens: [],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 5,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["fall", "winter"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("red lentils", 1.5, "cups", "pantry"),
      ing("onion", 1, "count", "produce"),
      ing("carrots", 2, "count", "produce"),
      ing("garlic", 3, "cloves", "produce"),
      ing("cumin", 2, "tsp", "spices"),
      ing("lemon", 1, "count", "produce"),
      ing("olive oil", 2, "tbsp", "pantry"),
      ing("crusty bread", 1, "loaf", "grains"),
    ],
    tags: ["healthy", "vegan", "comfort-food"],
  },

  // ── ETHIOPIAN ──
  {
    title: "Misir Wot",
    cuisine: "ethiopian",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 40,
    allergens: [],
    kid_friendly: false,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["fall", "winter"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("red lentils", 1.5, "cups", "pantry"),
      ing("onion", 3, "count", "produce"),
      ing("garlic", 4, "cloves", "produce"),
      ing("ginger", 1, "inch", "produce"),
      ing("berbere spice", 2, "tbsp", "spices"),
      ing("tomato paste", 2, "tbsp", "pantry"),
      ing("rice", 1.5, "cups", "grains"),
    ],
    tags: ["vegan", "spicy"],
  },

  // ── MORE VARIETY ──
  {
    title: "Fish Tacos",
    cuisine: "mexican",
    vegetarian: false,
    protein_type: "fish",
    cook_minutes: 25,
    allergens: ["fish"],
    kid_friendly: true,
    makes_leftovers: false,
    leftovers_score: 0,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["summer"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("white fish fillets", 1.5, "lb", "protein"),
      ing("corn tortillas", 12, "count", "grains"),
      ing("cabbage", 2, "cups", "produce"),
      ing("avocado", 2, "count", "produce"),
      ing("lime", 2, "count", "produce"),
      ing("sour cream", 0.5, "cup", "dairy"),
      ing("chili powder", 1, "tsp", "spices"),
    ],
    tags: ["quick", "crowd-pleaser"],
  },
  {
    title: "Pesto Pasta",
    cuisine: "italian",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 20,
    allergens: ["gluten", "dairy", "nuts"],
    kid_friendly: true,
    makes_leftovers: false,
    leftovers_score: 1,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["summer"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("penne pasta", 1, "lb", "grains"),
      ing("basil pesto", 0.5, "cup", "pantry"),
      ing("cherry tomatoes", 1, "pint", "produce"),
      ing("parmesan", 0.5, "cup", "dairy"),
      ing("pine nuts", 2, "tbsp", "pantry"),
    ],
    tags: ["quick", "kid-favorite"],
  },
  {
    title: "Miso Glazed Cod",
    cuisine: "japanese",
    vegetarian: false,
    protein_type: "fish",
    cook_minutes: 25,
    allergens: ["soy", "fish"],
    kid_friendly: false,
    makes_leftovers: false,
    leftovers_score: 0,
    difficulty: "medium",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["winter"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("cod fillets", 1.5, "lb", "protein"),
      ing("white miso paste", 3, "tbsp", "pantry"),
      ing("mirin", 2, "tbsp", "pantry"),
      ing("rice", 1.5, "cups", "grains"),
      ing("bok choy", 4, "count", "produce"),
      ing("sesame seeds", 1, "tbsp", "spices"),
    ],
    tags: ["healthy", "elegant"],
  },
  {
    title: "Mushroom Risotto",
    cuisine: "italian",
    vegetarian: true,
    protein_type: null,
    cook_minutes: 40,
    allergens: ["dairy"],
    kid_friendly: false,
    makes_leftovers: true,
    leftovers_score: 3,
    difficulty: "hard",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: ["fall", "winter"],
    frequency_cap_per_month: null,
    ingredients: [
      ing("arborio rice", 1.5, "cups", "grains"),
      ing("mushrooms", 12, "oz", "produce"),
      ing("onion", 1, "count", "produce"),
      ing("garlic", 3, "cloves", "produce"),
      ing("white wine", 0.5, "cup", "pantry"),
      ing("parmesan", 0.5, "cup", "dairy"),
      ing("butter", 3, "tbsp", "dairy"),
      ing("vegetable broth", 4, "cups", "pantry"),
    ],
    tags: ["elegant", "comfort-food"],
  },
  {
    title: "Turkey Meatballs",
    cuisine: "american",
    vegetarian: false,
    protein_type: "turkey",
    cook_minutes: 35,
    allergens: ["gluten"],
    kid_friendly: true,
    makes_leftovers: true,
    leftovers_score: 4,
    difficulty: "easy",
    source_type: "seeded",
    source_name: null,
    source_url: null,
    seasonal_tags: [],
    frequency_cap_per_month: null,
    ingredients: [
      ing("ground turkey", 1.5, "lb", "protein"),
      ing("breadcrumbs", 0.5, "cup", "pantry"),
      ing("egg", 1, "count", "dairy"),
      ing("marinara sauce", 2, "cups", "pantry"),
      ing("spaghetti", 1, "lb", "grains"),
      ing("garlic", 2, "cloves", "produce"),
      ing("parsley", 0.25, "cup", "produce"),
    ],
    tags: ["comfort-food", "kid-favorite"],
  },
];
